### ISSUE TITLE
Provide example using controls

### ISSUE THREAD

**Issue by holgerbrandl** [CuriousNikhil/k5-compose#3]
Similar to how sliders and buttons are supported in p5.js (e.g. see https://p5js.org/examples/dom-slider.html), it would be great to learn controls that could be used with k5.

This would be useful to add interactivity, e.g
* Toggle effects with checkboxes
* Adjust particle number with slider
* Reset animation with button

**Comment by CuriousNikhil** [comment]
Thanks a lot for the suggestions! I'll try to add those features.
However, please feel free to raise PR. I would be more than happy to accept.

**Comment by CuriousNikhil** [comment]
Released with [v1.0.0](https://github.com/CuriousNikhil/k5-compose/releases/tag/v1.0.0)
