### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SammyO** [CuriousNikhil/k5-compose#5]
Hi there,

Love this library, thanks for creating it. The examples and demos look amazing :)
I have been using this library mainly for it's Perlin noise generation (as my app doesn't use Compose yet, I can't use all your library's capabilities). When it comes to Perlin noise, it would be useful if the output could be normalised to -1 to 1, so I can use it as a scaling factor (e.g. drawing time-based scaling transformations).

**Comment by SammyO** [comment]
Scratch that, I misunderstood the algorithm :)

**Comment by CuriousNikhil** [comment]
Please feel free to modify suggest new changes and raise PR! I would be happy to merge it. 😄
